---
title: "linear_models"
output: github_document
date: "2024-11-08"
---

```{r}
library(tidyverse)
library(p8105.datasets)
```

Do some data cleaning

```{r}
data("nyc_airbnb")
nyc_airbnb=
  nyc_airbnb |> 
  mutate(stars= review_scores_location/2) |> 
  rename(
    borough =neighbourhood_group,
    neighborhood= neighbourhood
  ) |> 
  filter(
    borough != "Staten Island"
  ) |> 
  select(price, stars, borough, neighborhood, room_type) |> 
  mutate(
    borough=fct_infreq(borough),
    room_type=fct_infreq(room_type)
  )
```
adding last mutate step used to change ref category in order of freq instead of ABC order 

## Fit some models
start relatively simple

```{r}
fit= lm(price ~ stars, data=nyc_airbnb)

summary(fit)

names(summary(fit))

coef(fit)

broom::tidy(fit)


fit |> 
  broom::tidy() |> 
  select(term, estimate, p.value)

fit |> 
  broom::glance()
```
most often uses broom::tidy() line of code bc will format in form of a df and can select and stuff like that


Try a bit more complex
```{r}
fit= 
  lm(price~stars + borough, data=nyc_airbnb)

fit |> 
  broom::tidy() |> 
  select(term, estimate, p.value) |> 
  mutate(
    term= str_replace(term, "borough", "Borough: ")
  ) |> 
  knitr::kable(digits=3)
  
```

